### PR TITLE
Update to recent RxJava

### PR DESCRIPTION
**Pull request by avsej**
In recent RxJava some interfaces has been renamed, and also `Java::Rx::Observable::OnSubscribe` now also inherits from `Java::RxFunctions::Action` so wrappers collection turned to array to check them in predictable order (ruby 1.8 does not guarantee ordered hashes)

### CODE REVIEW

**Comment by avsej** [comment]
It also includes and expands #3

**Comment by avsej** [comment]
@benjchristensen is this project alive?

**Comment by benjchristensen** [comment]
Not very. We have never gotten interest from the JRuby community to contribute and maintain it and no one at Netflix uses it. 

I can merge this change but this project needs someone with JRuby experience to own it. 

Are you interested in helping?

**Comment by avsej** [comment]
I would like to make it a bit friendly by exposing package through rubygems

**Comment by benjchristensen** [comment]
That would be great. I'll merge your work and release when you're ready.

**Pull request merged**
